name: Publish to PyPi

on:
  workflow_call:
    inputs:
      repository:
        description: Repository to publish to
        type: string
        required: true
      password:
        description: Repository password
        type: string
        required: true
      python-version:
        description: Version of Python
        type: string
        required: false
        default: "3.8"

jobs:
  publish-to-repo:
    name: Publish to repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version:  ${{ inputs.python-version }}
      - name: Install poetry
        run: python -m pip install --upgrade pip poetry poetry-plugin-export
      - name: Setup pipenv virtual environment (and project dependencies)
        run: poetry install
      - name: Publish
        run: poetry publish -r ${{ inputs.repository }} -u __token__ -p ${{ inputs.password }} --dry-run
