name: Publish Package

on:
  workflow_call:
    inputs:
      git-ref:
        description: What git tag/branch to release
        type: string
        required: true
        default: dev
      repository:
        description: Repository to publish to
        type: string
        required: true
      python-version:
        description: Version of Python
        type: string
        required: false
        default: "3.8"

  workflow_dispatch:
    inputs:
      git-ref:
        description: What git tag/branch to release
        type: string
        required: true
        default: dev
      repository:
        description: Repository to publish to
        type: choice
        options:
          - testpypi
          - pypi
        required: true
      python-version:
        description: Version of Python
        type: string
        required: false
        default: "3.8"

jobs:
  publish-to-repo:
    name: Publish to repo
    environment: Publishing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version:  ${{ inputs.python-version }}
      - name: Install poetry
        run: python -m pip install --upgrade pip poetry poetry-plugin-export
      - name: Configure poetry repositories
        run: |
          case "${{ inputs.repository }}" in
            testpypi)
              poetry config repositories.testpypi https://test.pypi.org/legacy/
              poetry config http-basic.testpypi __token__ "${{ secrets.PYPI_TEST_TOKEN }}"
              ;;
            pypi)
              poetry config http-basic.pypi __token__ "${{ secrets.PYPI_PROD_TOKEN }}"
              ;;
            *)
              echo "Invalid repository requested: ${{ inputs.repository }}"
              exit 1
              ;;
          esac
      - name: Setup virtual environment (and project dependencies)
        run: poetry install
      - name: Publish
        run: poetry publish --build -r ${{ inputs.repository }} --dry-run
