name: Release version

on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: What git tag/branch to release
        type: string
        required: true
        default: main
      python-version:
        description: What version of Python to use
        type: string
        required: false
        default: "3.8"

jobs:
  tag-commit:
    name: Tag and publish
    runs-on: ubuntu-latest
    environment: Publishing
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.git-ref }}
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version:  ${{ inputs.python-version }}
      - name: Install poetry
        run: python -m pip install --upgrade pip poetry
      - name: Config git user
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Tag version
        run: |
          VERSION_TAG="v$(poetry version -s)"
          git tag -a "$VERSION_TAG" -m "Releasing version $VERSION_TAG" 
          git push origin "$VERSION_TAG"
      - name: Increment version in dev
        run: |
          git fetch origin
          git checkout dev
          poetry version patch
          git add pyproject.toml
          git commit -m"Updated version to $(poetry version -s)"
          git push origin dev
          
