name: Release version

on:
  workflow_dispatch:
    inputs:
      python-version:
        description: What version of Python to use
        type: string
        required: false
        default: "3.8"

jobs:
  tag-commit:
    name: Tag and publish
    runs-on: ubuntu-latest
    environment: Publishing
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version:  ${{ inputs.python-version }}
      - name: Install poetry
        run: python -m pip install --upgrade pip poetry
      - name: Tag version
        run: |
          VERSION_TAG="v$(poetry version -s)"
          git tag -a "$VERSION_TAG"
          git push origin "$VERSION_TAG"
