name: Development Actions

on:
  workflow_call:
    inputs:
      python-version:
        description: What version of Python to use
        type: string
        default: 3.8
        required: false

jobs:
  test-build:
    name: Test and Package Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version:  ${{ inputs.python-version }}
      - name: Install poetry
        run: python -m pip install --upgrade pip poetry poetry-plugin-export
      - name: Setup pipenv virtual environment (and project dependencies)
        run: poetry install --with dev
      - name: Run unit tests
        run: ./run-tests.sh
      - name: Unit Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Unit Test Results
          path: ./test_results/results.xml
          reporter: java-junit
      - name: Coverage Report
        uses: 5monkeys/cobertura-action@v13
        with:
          path: ./test_results/coverage.xml
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          minimum_coverage: 75
          show_line: true
          show_missing: true
          skip_covered: false
          report_name: Coverage Report
      - name: Build wheel and source distribution
        run: poetry build
